### ISSUE TITLE
Dropdowns in form

### ISSUE THREAD

**Issue by jamime** [websemantics/semantic-dojo-styles#1]
I'm currently looking at styling components inside of a `dijit/Form/Form` currently `dijit/Form/ValidationTextBox` works with the `ui input` classes applied. However, when I apply `ui dropdown` classes to `dijit/Form/Select` it does not style correctly. 

Is this something that has not yet been implemented or am I using it wrong?

**Comment by jamime** [comment]
Update:
It appears that the dropwdown rules for `.dijitSelect .dijitArrowButtonInner` are overridden. This produces an extra floating div (this is the old arrow).

**Comment by jamime** [comment]
This was due to a nesting issue. I had a custom widget that added an extra div between 
`.ui.form .field` and `.selection.dropdown` therefore the selector `.ui.form .field > .selection.dropdown` was not matching. I modified my custom widget.

**Comment by websemantics** [comment]
There's a bit to cover still with form widgets, but glad you've fixed your issue, ..
